import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="fixed top-0 left-0 right-0 px-96 flex gap-6 text-white-900 p-4 bg-black-800 shadow-md z-50">
          <Link href="/" className="text-xl hover:underline">
            Andrew.
          </Link>
          <Link
            href="/"
            className="hover:underline-offset-4 hover:text-green-500 hover:underline"
          >
            Home
          </Link>
          <Link
            href="/about"
            className="hover:underline-offset-4 hover:text-green-500 hover:underline"
          >
            Services
          </Link>
          <Link
            href="/services"
            className="hover:underline-offset-4 hover:text-green-500 hover:underline"
          >
            Resume
          </Link>
          <Link
            href="/services"
            className="hover:underline-offset-4 hover:text-green-500 hover:underline"
          >
            Work
          </Link>
          <Link
            href="/contact"
            className="hover:underline-offset-4 hover:text-green-500 hover:underline"
          >
            Contact
          </Link>
        </nav>
        <main className="p-8 mt-16">{children}</main>{" "}
        {/* Added margin-top for spacing */}
      </body>
    </html>
  );
}
